# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapiapp', '0004_sentimentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentdata',
            old_name='isFake',
            new_name='containsHateSpeech',
        ),
        migrations.RenameField(
            model_name='sentimentdata',
            old_name='text',
            new_name='words',
        ),
        migrations.AddField(
            model_name='sentimentdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
